# Configuration options are documented at:
# http://about.travis-ci.org/docs/user/languages/ruby/
language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - tests/Gemfile
branches:
  only:
    - master
script: cd tests; bundle exec rake
